# Generated by Django 4.2.23 on 2025-06-19 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_taskexecution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="host",
            name="ssh_key_name",
        ),
        migrations.CreateModel(
            name="SSHKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "private_key",
                    django_cryptography.fields.encrypt(
                        models.TextField(help_text="Encrypted private SSH key.")
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SSH key fingerprint (e.g., SHA256). Optional, can be generated client-side or via a utility.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "associated_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssh_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["associated_user", "name"],
                "unique_together": {("associated_user", "name")},
            },
        ),
        migrations.AddField(
            model_name="host",
            name="ssh_key",
            field=models.ForeignKey(
                blank=True,
                help_text="SSH Key to use for this host.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hosts",
                to="api.sshkey",
            ),
        ),
    ]
