---
# Webserver 任务
- name: Install Nginx
  apt:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes
